# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"0\n\nAddRequest\x12\x10\n\x08operand1\x18\x01 \x01(\x05\x12\x10\n\x08operand2\x18\x02 \x01(\x05\"5\n\x0fSubtractRequest\x12\x10\n\x08operand1\x18\x01 \x01(\x05\x12\x10\n\x08operand2\x18\x02 \x01(\x05\"5\n\x0fMultiplyRequest\x12\x10\n\x08operand1\x18\x01 \x01(\x02\x12\x10\n\x08operand2\x18\x02 \x01(\x02\"3\n\rDivideRequest\x12\x10\n\x08operand1\x18\x01 \x01(\x02\x12\x10\n\x08operand2\x18\x02 \x01(\x02\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\"\n\x10SubtractResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\"\n\x10MultiplyResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\" \n\x0e\x44ivideResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\x32\xbb\x01\n\nCalculator\x12 \n\x03\x41\x64\x64\x12\x0b.AddRequest\x1a\x0c.AddResponse\x12/\n\x08Subtract\x12\x10.SubtractRequest\x1a\x11.SubtractResponse\x12/\n\x08Multiply\x12\x10.MultiplyRequest\x1a\x11.MultiplyResponse\x12)\n\x06\x44ivide\x12\x0e.DivideRequest\x1a\x0f.DivideResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ADDREQUEST']._serialized_start=20
  _globals['_ADDREQUEST']._serialized_end=68
  _globals['_SUBTRACTREQUEST']._serialized_start=70
  _globals['_SUBTRACTREQUEST']._serialized_end=123
  _globals['_MULTIPLYREQUEST']._serialized_start=125
  _globals['_MULTIPLYREQUEST']._serialized_end=178
  _globals['_DIVIDEREQUEST']._serialized_start=180
  _globals['_DIVIDEREQUEST']._serialized_end=231
  _globals['_ADDRESPONSE']._serialized_start=233
  _globals['_ADDRESPONSE']._serialized_end=262
  _globals['_SUBTRACTRESPONSE']._serialized_start=264
  _globals['_SUBTRACTRESPONSE']._serialized_end=298
  _globals['_MULTIPLYRESPONSE']._serialized_start=300
  _globals['_MULTIPLYRESPONSE']._serialized_end=334
  _globals['_DIVIDERESPONSE']._serialized_start=336
  _globals['_DIVIDERESPONSE']._serialized_end=368
  _globals['_CALCULATOR']._serialized_start=371
  _globals['_CALCULATOR']._serialized_end=558
# @@protoc_insertion_point(module_scope)
